# Generated by Django 3.1.2 on 2020-10-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='infomation',
        ),
    ]
