# Generated by Django 3.1.2 on 2020-11-02 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='des',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='contact_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
