# Generated by Django 3.1.2 on 2020-10-29 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_infomationmodel_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomationmodel',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
