# Generated by Django 3.1.2 on 2020-10-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_infomationmodel_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='about',
            field=models.CharField(max_length=2500),
        ),
    ]
