# Generated by Django 3.1.2 on 2020-10-30 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_skillmodel_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmodel',
            name='des',
        ),
        migrations.AddField(
            model_name='infomationmodel',
            name='skill_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
