# Generated by Django 3.1.2 on 2020-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_picturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='profile_picture',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
