# Generated by Django 3.1.2 on 2020-10-31 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20201031_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='percent',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
