# Generated by Django 3.1.2 on 2020-10-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_skillmodel_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
