# Generated by Django 3.1.2 on 2020-10-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_auto_20201031_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='percent',
            field=models.IntegerField(blank=True),
        ),
    ]
