# Generated by Django 3.1.2 on 2020-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_auto_20201031_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomationmodel',
            old_name='skill_des',
            new_name='skilldes',
        ),
        migrations.AlterField(
            model_name='infomationmodel',
            name='about',
            field=models.CharField(max_length=250),
        ),
    ]
